### ISSUE TITLE
Some of the links are no longer working, for pdf hosted on Sony site.

### ISSUE THREAD

**Issue by hanpuliu-charles** [nullableVoidPtr/nfcf-info#2]
Hi there, love what you are doing(basically what I have tried to do spending way too many hours but many times better!) Just a comment, is it possible to save a copy of the reference in the repository. Some of the links are no longer working(for example, reference 5 on this page; [IC info](https://nullablevoidptr.github.io/nfcf-info/IC-chips/card). Is it possible to upload the original pdf to the repo so that we can still view the infomation? Thanks!

Also, I have some dual mode cards, Chinese mainland issued t-union with octopus function as well as octopus card with t-union functionality, they are dual mode 14443A and 18092. I am currently away from home but could get you their IC code(i remember that they are different, as the mainland issued cards are not using a Sony inlay but rather a typical MOB with enamel wire coil, while the Octopus t-union has a sony branded inlay like the typical FeliCa cards.

**Comment by nullableVoidPtr** [comment]
Hi!

Thank you very much for your interest in this wiki. Unfortunately the [`refs.bib`](https://github.com/nullableVoidPtr/nfcf-info/blob/c086d65f0144edfa9a9a0eb174b6eea64e720c73/refs.bib) is still shoddily managed via Zotero throughout my research and some manual editing prior to committing, so it's likely the case that I have made an error with referencing this document. Please point them out as you see fit.

Due to an abundance of caution around copyright and intellectual property, I have elected to not host or mirror any referenced documents on this repository or adjacent. Unfortunately, there are also references to and traces of more interesting documents such as the several variations of a Security Reference Manual or the CJRC standard (サイバネ規格) which simply are not available anywhere.

I likely have pulled this particular reference from the [Internet Archive](https://web.archive.org/), and a quick search determines that this is likely the case as there are hits for those.

Regarding your dual mode cards; please do send in your IC codes! With the closed nature of the product, *absolutely **anything*** can help, from responses to external NFC commands, the IDm format, even to dissolving the card itself to identify the inlay serial (though that will be destructive of course!). I'd prefer that any exploratory findings should be posted to the repository's [discussions](https://github.com/nullableVoidPtr/nfcf-info/discussions) rather than issues which should only concern mistakes, errors and omissions like the one you identified.

I'll leave this issue open pending a quick scrub through the bibliography to amend dead links when I am next available to.
